name: Crear APK CalmBox

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.0'

      - name: Compilar APK
        run: gradle assembleDebug

      - name: Crear CalmBox.apk
        run: cp app/build/outputs/apk/debug/app-debug.apk CalmBox.apk

      - name: Publicar APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: calmbox-v1
          name: CalmBox v1
          files: CalmBox.apk
